### ISSUE TITLE
Cannot Register with whisper push (Bad response 417)

### ISSUE THREAD

**Issue by priceaj** [CyanogenMod/android_external_whispersystems_WhisperPush#13]
Running CM11 20141119 Nightly on Nexus 5, build Info:
build.board: hammerhead
build.bootloader: HHZ11k
build.brand: google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: hammerhead
build.display: cm_hammerhead-userdebug 4.4.4 KTU84Q eee2ffb26f test-keys
build.fingerprint: google/hammerhead/hammerhead:4.4.4/KTU84P/1227136:user/release-keys
build.hardware: hammerhead
build.host: cyanogenmod
build.id: KTU84Q
build.manufacturer: LGE
build.model: Nexus 5
build.product: hammerhead
build.radio: M8974A-2.0.50.1.16
build.serial: 05353091f0c9e0ec
build.tags: test-keys
build.time: 1416418040000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: eee2ffb26f
version.release: 4.4.4
version.sdk_int: 19

Issue:

Going into Settings > Privacy > WhisperPush > Register

Enter phone number in format +44XXXXXXXXXX

Click Register > Continue

Process fails at Waiting for SMS verificaton

logcat:

11-23 10:19:30.616 W/PushServiceSocket(20650): Push service URL: https://whisperpush.cyanogenmod.org
11-23 10:19:30.616 W/PushServiceSocket(20650): Opening URL: https://whisperpush.cyanogenmod.org/v1/accounts/sms/code/+44XXXXXXXXXX
11-23 10:19:36.846 W/RegistrationService(20650): Got a challenge broadcast...
11-23 10:19:36.876 W/PushServiceSocket(20650): Push service URL: https://whisperpush.cyanogenmod.org
11-23 10:19:36.876 W/PushServiceSocket(20650): Opening URL: https://whisperpush.cyanogenmod.org/v1/accounts/code/439363
11-23 10:19:37.516 W/PushServiceSocket(20650): PUT  --  {"signalingKey":"**REMOVED**"}
11-23 10:19:37.806 W/RegistrationService(20650): java.io.IOException: Bad response: 417 
11-23 10:19:37.806 W/RegistrationService(20650):    at org.whispersystems.textsecure.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:322)
11-23 10:19:37.806 W/RegistrationService(20650):    at org.whispersystems.textsecure.push.PushServiceSocket.makeRequest(PushServiceSocket.java:283)
11-23 10:19:37.806 W/RegistrationService(20650):    at org.whispersystems.textsecure.push.PushServiceSocket.verifyAccount(PushServiceSocket.java:76)
11-23 10:19:37.806 W/RegistrationService(20650):    at org.whispersystems.whisperpush.service.RegistrationService.handleRegistrationIntent(RegistrationService.java:256)
11-23 10:19:37.806 W/RegistrationService(20650):    at org.whispersystems.whisperpush.service.RegistrationService.access$200(RegistrationService.java:71)
11-23 10:19:37.806 W/RegistrationService(20650):    at org.whispersystems.whisperpush.service.RegistrationService$1.run(RegistrationService.java:124)
11-23 10:19:37.806 W/RegistrationService(20650):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-23 10:19:37.806 W/RegistrationService(20650):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-23 10:19:37.806 W/RegistrationService(20650):    at java.lang.Thread.run(Thread.java:811)
11-23 10:20:14.538 I/Timeline(20650): Timeline: Activity_idle id: android.os.BinderProxy@650979e0 time:110484010

Googling points to the problem to be with being registered on another service. 

Tried installing TextSecure and registering on service... This worked correctly.

Unregistered from TextSecure as follows:

TextSecure > Settings > Uncheck Push Messages > OK

Uninstalled and also unregistered via:

https://whispersystems.org/textsecure/unregister/ (found link here: https://github.com/WhisperSystems/TextSecure/issues/917)

Using all forms of number:
+44XXXXXXXXXX
+440XXXXXXXXXX
0XXXXXXXXXXX selecting country United Kingdom

same issue

11-23 10:34:42.088 W/PushServiceSocket(2551): Push service URL: https://whisperpush.cyanogenmod.org
11-23 10:34:42.088 W/PushServiceSocket(2551): Opening URL: https://whisperpush.cyanogenmod.org/v1/accounts/sms/code/+44XXXXXXXXXX
11-23 10:34:45.648 W/RegistrationService(2551): Got a challenge broadcast...
11-23 10:34:45.698 W/PushServiceSocket(2551): Push service URL: https://whisperpush.cyanogenmod.org
11-23 10:34:45.698 W/PushServiceSocket(2551): Opening URL: https://whisperpush.cyanogenmod.org/v1/accounts/code/767362
11-23 10:34:46.378 W/PushServiceSocket(2551): PUT  --  {"signalingKey":"_REMOVED_"}
11-23 10:34:46.648 W/RegistrationService(2551): java.io.IOException: Bad response: 417 
11-23 10:34:46.648 W/RegistrationService(2551):     at org.whispersystems.textsecure.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:322)
11-23 10:34:46.648 W/RegistrationService(2551):     at org.whispersystems.textsecure.push.PushServiceSocket.makeRequest(PushServiceSocket.java:283)
11-23 10:34:46.648 W/RegistrationService(2551):     at org.whispersystems.textsecure.push.PushServiceSocket.verifyAccount(PushServiceSocket.java:76)
11-23 10:34:46.648 W/RegistrationService(2551):     at org.whispersystems.whisperpush.service.RegistrationService.handleRegistrationIntent(RegistrationService.java:256)
11-23 10:34:46.648 W/RegistrationService(2551):     at org.whispersystems.whisperpush.service.RegistrationService.access$200(RegistrationService.java:71)
11-23 10:34:46.648 W/RegistrationService(2551):     at org.whispersystems.whisperpush.service.RegistrationService$1.run(RegistrationService.java:124)
11-23 10:34:46.648 W/RegistrationService(2551):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-23 10:34:46.648 W/RegistrationService(2551):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-23 10:34:46.648 W/RegistrationService(2551):     at java.lang.Thread.run(Thread.java:811)

**Comment by meepoSenpai** [comment]
I am experiencing the same error, and can't register or unregister from the CM-WhisperPush service.
When trying to register via phone number I recieve a code, but it won't be able to connect to the server twice, and the third time it will say I've entered the code wrong too many times (even though I correctly entered the code)

When trying to unregister from CM-Whisperpush I don't even recieve any text message with a validation code.

**Comment by foresto** [comment]
I recently installed CyanogenMod on a new phone, so I thought I'd try WhisperPush again. No luck; this bug still exists; WhisperPush is still broken.

cm-12.1-20151023-NIGHTLY-amami
